### ISSUE TITLE
Very interesting game

### ISSUE THREAD

**Issue by Jeffxz** [goeroeg/ld-learn#1]
Hi
I found this is quite interesting especially for education.
It's not a issue but rather than a question. When I played I felt a bit confusing. What is this (attached image)?
![what-is-this](https://user-images.githubusercontent.com/875328/184179504-081568f9-4f57-4557-9167-3f1435dd35ed.png)
I
Also, is there any map from beginning?
Overall I really like what you are doing and please feel free to contact me zhengxu7806@gmail.com if would like to discuss more about games for education.

**Comment by goeroeg** [comment]
Thank you @Jeffxz for trying out my game, I appreciate it.
For your question: what you see in the image are the crystals that have to be collected to advance in the game. The line above is only there for a better visibility from the distance. A minimap becomes available after 2-3 crystals collected.
